# Generated by Django 4.2.27 on 2025-12-24 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='male', max_length=20)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(default='user', max_length=40)),
                ('subscription_type', models.CharField(default='free', max_length=40)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
