# Generated by Django 4.2.27 on 2026-01-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(default='English text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='English text', max_length=100),
            preserve_default=False,
        ),
    ]
